### ISSUE TITLE
Picture with caption

### ISSUE THREAD

**Issue by vasilisvg** [lhafkamp/minor-cssttr#4]
Hoei, wat ziet die transitie er kicke uit! Hier is nog wel een andere uitdaging:

Het plaatje moet _altijd_ helemaal zichtbaar zijn in elke viewport. Dus maximaal `100vh`, en maximaal `100vw`. Bovendien moet je ook altijd kunnen zien dat er een onderschrift is. En dit moet werken met een landscape en een portrait plaatje …
En kan je je nog herinneren hoeveel `em` breed een paragraaf maximaal mag zijn?

**Comment by lhafkamp** [comment]
Dit is het enige wat mij niet gelukt is.

Ik heb hier ontzettend mee geworsteld maar ben er niet uitgekomen hoe ik hem gecentreerd kan krijgen vanuit de target state. Ook weet ik niet hoe ik uit de target state kom. Zou ik hier wat hulp mee kunnen krijgen na de vakantie?
